// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9rwQQiYM1QFyGYvFTGQJx-PNt8Z_wus8',
    appId: '1:200979994048:web:ec64bcceae4d558cc9a425',
    messagingSenderId: '200979994048',
    projectId: 'race-tracker-2f208',
    authDomain: 'race-tracker-2f208.firebaseapp.com',
    storageBucket: 'race-tracker-2f208.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCroTUWM_toX1R-BqKExBhqv_1SYLZRcEo',
    appId: '1:200979994048:android:3acd8bfb151e329cc9a425',
    messagingSenderId: '200979994048',
    projectId: 'race-tracker-2f208',
    storageBucket: 'race-tracker-2f208.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjIHbtrkiGZMauDasicA96H_8ykoK-yOM',
    appId: '1:200979994048:ios:05e351f5c888dc4dc9a425',
    messagingSenderId: '200979994048',
    projectId: 'race-tracker-2f208',
    storageBucket: 'race-tracker-2f208.appspot.com',
    iosBundleId: 'com.example.raceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjIHbtrkiGZMauDasicA96H_8ykoK-yOM',
    appId: '1:200979994048:ios:05e351f5c888dc4dc9a425',
    messagingSenderId: '200979994048',
    projectId: 'race-tracker-2f208',
    storageBucket: 'race-tracker-2f208.appspot.com',
    iosBundleId: 'com.example.raceTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9rwQQiYM1QFyGYvFTGQJx-PNt8Z_wus8',
    appId: '1:200979994048:web:2c9cd34678860ad0c9a425',
    messagingSenderId: '200979994048',
    projectId: 'race-tracker-2f208',
    authDomain: 'race-tracker-2f208.firebaseapp.com',
    storageBucket: 'race-tracker-2f208.appspot.com',
  );
}
